import { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = "https://www.sellertoolsuite.com";

  const routes = [
    "",

    

    "/etsy",
    "/etsy/profit-calculator",
    "/etsy/fee-calculator",
    "/etsy/pricing-calculator",
    "/etsy/break-even-calculator",
    "/etsy/sales-goal-calculator",
    "/etsy/ad-roi-calculator",
    "/etsy/discount-impact-calculator",
    "/etsy/conversion-rate-calculator",
    "/etsy/listing-roi-calculator",
    "/etsy/shipping-profit-calculator",
    "/etsy/bundle-pricing-calculator",
    "/etsy/inventory-restock-calculator",
    "/etsy/refund-impact-calculator",
    "/etsy/labor-cost-calculator",
    "/etsy/product-cost-calculator",
    "/etsy/about",
    "/etsy/privacy-policy",
    "/etsy/terms",

    "/etsy/how-etsy-fees-work",
    "/etsy/how-to-price-etsy-products",
    "/etsy/profit-margin-guide",
    "/etsy/seller-cost-checklist",
    "/etsy/shipping-cost-guide",
    "/etsy/free-shipping-strategy",
    "/etsy/offsite-ads-fees",
    "/etsy/discount-strategy-guide",
    "/etsy/refunds-and-returns-cost-guide",
    "/etsy/listing-roi-guide",
    "/etsy/conversion-rate-guide",
    "/etsy/inventory-restock-guide",
    "/etsy/sales-goal-planning-guide",
    "/etsy/bundle-pricing-guide",
    "/etsy/seller-resources",

    "/ebay",
    "/ebay/profit-calculator",
    "/ebay/fee-calculator",
    "/ebay/pricing-calculator",
    "/ebay/shipping-profit-calculator",
    "/ebay/break-even-calculator",
    "/ebay/promoted-listing-roi-calculator",
    "/ebay/offer-discount-calculator",
"/ebay/sales-goal-calculator",
"/ebay/conversion-rate-calculator",
"/ebay/listing-roi-calculator",
"/ebay/refund-impact-calculator",
"/ebay/inventory-restock-calculator",
"/ebay/store-fee-calculator",
"/ebay/international-shipping-calculator",
"/ebay/product-cost-calculator",
"/ebay/how-ebay-fees-work",
"/ebay/how-to-price-ebay-products",
"/ebay/profit-margin-guide",
"/ebay/seller-cost-checklist",
"/ebay/shipping-cost-guide",
"/ebay/free-shipping-strategy",
"/ebay/promoted-listing-fees",
"/ebay/discount-strategy-guide",
"/ebay/refunds-and-returns-cost-guide",
"/ebay/listing-roi-guide",
"/ebay/conversion-rate-guide",
"/ebay/inventory-restock-guide",
"/ebay/sales-goal-planning-guide",
"/ebay/store-fee-guide",
"/ebay/seller-resources",

    "/amazon",
    "/amazon/fba-profit-calculator",
    "/amazon/fee-calculator",
    "/amazon/pricing-calculator",
    "/amazon/ppc-roi-calculator",
    "/amazon/break-even-calculator",
    "/amazon/fbm-profit-calculator",
    "/amazon/referral-fee-calculator",
    "/amazon/storage-fee-calculator",
    "/amazon/product-cost-calculator",
    "/amazon/inventory-restock-calculator",
    "/amazon/sales-goal-calculator",
    "/amazon/conversion-rate-calculator",
    "/amazon/refund-impact-calculator",
    "/amazon/listing-roi-calculator",
    "/amazon/fba-vs-fbm-calculator",
    "/amazon/how-amazon-fees-work",
    "/amazon/how-to-price-amazon-products",
    "/amazon/profit-margin-guide",
    "/amazon/seller-cost-checklist",
    "/amazon/fba-cost-guide",
    "/amazon/fbm-shipping-cost-guide",
    "/amazon/ppc-fees-explained",
    "/amazon/discount-strategy-guide",
    "/amazon/refunds-and-returns-cost-guide",
    "/amazon/listing-roi-guide",
    "/amazon/conversion-rate-guide",
    "/amazon/inventory-restock-guide",
    "/amazon/sales-goal-planning-guide",
    "/amazon/fba-vs-fbm-guide",
    "/amazon/seller-resources",

    "/shopify",
    "/shopify/profit-calculator",
    "/shopify/fee-calculator",
    "/shopify/pricing-calculator",
    "/shopify/ad-roi-calculator",
    "/shopify/break-even-calculator",
    "/shopify/product-cost-calculator",
    "/shopify/shipping-profit-calculator",
    "/shopify/discount-impact-calculator",
    "/shopify/refund-impact-calculator",
    "/shopify/conversion-rate-calculator",
    "/shopify/listing-roi-calculator",
    "/shopify/inventory-restock-calculator",
    "/shopify/sales-goal-calculator",
    "/shopify/bundle-pricing-calculator",
    "/shopify/subscription-profit-calculator",
    "/shopify/how-shopify-fees-work",
    "/shopify/how-to-price-shopify-products",
    "/shopify/profit-margin-guide",
    "/shopify/seller-cost-checklist",
    "/shopify/shipping-cost-guide",
    "/shopify/ad-spend-strategy-guide",
    "/shopify/discount-strategy-guide",
    "/shopify/refunds-and-returns-cost-guide",
    "/shopify/conversion-rate-guide",
    "/shopify/listing-roi-guide",
    "/shopify/inventory-restock-guide",
    "/shopify/sales-goal-planning-guide",
    "/shopify/bundle-pricing-guide",
    "/shopify/subscription-pricing-guide",
    "/shopify/seller-resources",

    "/mercari",
    "/mercari/profit-calculator",
    "/mercari/fee-calculator",
    "/mercari/pricing-calculator",
    "/mercari/break-even-calculator",
    "/mercari/promotion-roi-calculator",
    "/mercari/shipping-profit-calculator",
"/mercari/product-cost-calculator",
"/mercari/refund-impact-calculator",
"/mercari/listing-roi-calculator",
"/mercari/inventory-restock-calculator",
"/mercari/sales-goal-calculator",
"/mercari/offer-profit-calculator",
"/mercari/free-shipping-calculator",
"/mercari/bundle-pricing-calculator",
"/mercari/sell-through-rate-calculator",
"/mercari/how-mercari-fees-work",
"/mercari/how-to-price-mercari-items",
"/mercari/profit-margin-guide",
"/mercari/seller-cost-checklist",
"/mercari/shipping-cost-guide",
"/mercari/promotion-strategy-guide",
"/mercari/refunds-and-returns-cost-guide",
"/mercari/listing-roi-guide",
"/mercari/inventory-restock-guide",
"/mercari/sales-goal-planning-guide",
"/mercari/offer-strategy-guide",
"/mercari/free-shipping-strategy",
"/mercari/bundle-pricing-guide",
"/mercari/sell-through-rate-guide",
"/mercari/seller-resources",

    "/poshmark",
    "/poshmark/fee-calculator",
    "/poshmark/profit-calculator",
    "/poshmark/pricing-calculator",
    "/poshmark/break-even-calculator",
    "/poshmark/offer-roi-calculator",
    "/poshmark/shipping-discount-calculator",
"/poshmark/product-cost-calculator",
"/poshmark/refund-impact-calculator",
"/poshmark/listing-roi-calculator",
"/poshmark/inventory-restock-calculator",
"/poshmark/sales-goal-calculator",
"/poshmark/bundle-pricing-calculator",
"/poshmark/closet-clear-out-calculator",
"/poshmark/closet-promotion-calculator",
"/poshmark/sell-through-rate-calculator",
"/poshmark/how-poshmark-fees-work",
"/poshmark/how-to-price-poshmark-items",
"/poshmark/profit-margin-guide",
"/poshmark/seller-cost-checklist",
"/poshmark/shipping-discount-guide",
"/poshmark/offer-strategy-guide",
"/poshmark/refunds-and-returns-cost-guide",
"/poshmark/listing-roi-guide",
"/poshmark/inventory-restock-guide",
"/poshmark/sales-goal-planning-guide",
"/poshmark/closet-clear-out-guide",
"/poshmark/closet-promotion-strategy-guide",
"/poshmark/bundle-pricing-guide",
"/poshmark/sell-through-rate-guide",
"/poshmark/seller-resources",

    "/facebook-marketplace",
    "/facebook-marketplace/profit-calculator",
    "/facebook-marketplace/pricing-calculator",
    "/facebook-marketplace/break-even-calculator",
    "/facebook-marketplace/negotiation-calculator",
    "/facebook-marketplace/shipping-profit-calculator",
    
  ];

  return routes.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: "weekly",
    priority: route === "" ? 1 : route === "/etsy" ? 0.9 : 0.7,
  }));
}