import Link from "next/link";

const listingRoiTypes = [
  {
    title: "Listing revenue",
    description:
      "The total money a listing brings in before subtracting Etsy fees, product costs, shipping, packaging, labor, ads, and refunds.",
  },
  {
    title: "Listing profit",
    description:
      "The money left after subtracting all listing-related costs from the revenue generated by that product.",
  },
  {
    title: "Ad spend impact",
    description:
      "The cost of Etsy ads or other promotion used to drive traffic to the listing.",
  },
  {
    title: "Conversion rate",
    description:
      "The percentage of listing visits that turn into orders. Low conversion can make ads or listing work less efficient.",
  },
  {
    title: "Refund and replacement losses",
    description:
      "Refunds, remakes, damaged packages, and replacements can reduce the real return from a listing.",
  },
  {
    title: "Time and maintenance cost",
    description:
      "Listings can require photo updates, SEO edits, messages, production time, restocking, and customer service.",
  },
];

const mistakes = [
  "Judging a listing only by sales volume instead of profit after costs.",
  "Keeping listings active even when they repeatedly lose money after ads or refunds.",
  "Ignoring labor, packaging, shipping, and product costs when reviewing listing performance.",
  "Increasing ad spend before checking whether the listing converts profitably.",
  "Comparing listings by revenue instead of profit, margin, and return on effort.",
  "Retiring listings too quickly without testing photos, title, pricing, tags, and conversion improvements.",
];

const checklist = [
  "Listing revenue over the review period.",
  "Product cost, materials, and labor.",
  "Etsy fees, payment processing, and listing fees.",
  "Shipping label cost and packaging supplies.",
  "Ad spend or promotion cost.",
  "Refunds, replacements, remakes, or return losses.",
  "Listing visits, orders, and conversion rate.",
  "Time spent maintaining, producing, restocking, or supporting the listing.",
];

const relatedTools = [
  {
    title: "Etsy Listing ROI Calculator",
    href: "/etsy/listing-roi-calculator",
  },
  {
    title: "Etsy Profit Calculator",
    href: "/etsy/profit-calculator",
  },
  {
    title: "Etsy Ad ROI Calculator",
    href: "/etsy/ad-roi-calculator",
  },
  {
    title: "Etsy Conversion Rate Calculator",
    href: "/etsy/conversion-rate-calculator",
  },
];

const workflow = [
  {
    title: "Measure revenue",
    description:
      "Start with the listing’s sales revenue during a clear review period.",
  },
  {
    title: "Subtract costs",
    description:
      "Include Etsy fees, product cost, shipping, packaging, labor, ads, refunds, and replacements.",
  },
  {
    title: "Review conversion",
    description:
      "Check visits, orders, conversion rate, and ad performance before deciding what to change.",
  },
  {
    title: "Choose an action",
    description:
      "Keep, improve, advertise, restock, bundle, discount, or retire the listing based on real return.",
  },
];

export default function EtsyListingRoiGuidePage() {
  return (
    <main className="mx-auto max-w-6xl px-6 py-12">
      <section className="max-w-3xl">
        <p className="text-sm font-bold uppercase tracking-wide text-blue-700">
          Etsy Seller Guide
        </p>

        <h1 className="mt-3 text-4xl font-bold tracking-tight text-gray-950">
          Etsy Listing ROI Guide
        </h1>

        <p className="mt-4 text-lg leading-8 text-gray-600">
          Etsy listing ROI helps sellers decide whether a product is worth
          keeping, improving, advertising, restocking, discounting, or retiring.
          A listing can generate sales while still producing weak profit if fees,
          product cost, shipping, labor, ads, refunds, and maintenance time are
          not included.
        </p>
      </section>

      <section className="mt-10 rounded-2xl border border-gray-300 bg-white p-6">
        <h2 className="text-2xl font-bold text-gray-950">
          Etsy listing ROI factors sellers should understand
        </h2>

        <div className="mt-6 grid gap-5 md:grid-cols-2">
          {listingRoiTypes.map((item) => (
            <div key={item.title} className="rounded-xl bg-gray-50 p-5">
              <h3 className="font-bold text-gray-950">{item.title}</h3>

              <p className="mt-3 text-sm leading-6 text-gray-600">
                {item.description}
              </p>
            </div>
          ))}
        </div>
      </section>

      <section className="mt-8 grid gap-8 lg:grid-cols-2">
        <div className="rounded-2xl border border-gray-300 bg-white p-6">
          <h2 className="text-2xl font-bold text-gray-950">
            Why Etsy listing ROI matters
          </h2>

          <div className="mt-4 space-y-4 text-sm leading-7 text-gray-600">
            <p>
              A listing can look successful from sales alone while still earning
              less than expected after fees, labor, product cost, shipping,
              packaging, ads, and refunds are included.
            </p>

            <p>
              Listing ROI helps sellers compare products more fairly. A listing
              with fewer sales may be better than a high-volume listing if it has
              stronger margin, fewer refunds, lower labor, and better ad
              efficiency.
            </p>

            <p>
              The safest approach is to review listing performance by profit,
              margin, conversion, refund risk, and time required before deciding
              whether to scale or retire the listing.
            </p>
          </div>
        </div>

        <div className="rounded-2xl border border-gray-300 bg-white p-6">
          <h2 className="text-2xl font-bold text-gray-950">
            Common Etsy listing ROI mistakes
          </h2>

          <ul className="mt-5 space-y-3 text-sm leading-6 text-gray-600">
            {mistakes.map((mistake) => (
              <li key={mistake} className="flex gap-3">
                <span className="mt-1 rounded-full bg-red-100 px-2 text-xs font-bold text-red-600">
                  ×
                </span>
                <span>{mistake}</span>
              </li>
            ))}
          </ul>
        </div>
      </section>

      <section className="mt-8 rounded-2xl border border-blue-300 bg-blue-50 p-6">
        <h2 className="text-2xl font-bold text-gray-950">
          Useful Etsy listing ROI calculators
        </h2>

        <p className="mt-3 text-sm leading-6 text-gray-700">
          Use these tools to estimate listing return, profit, ad performance,
          and conversion before increasing spend or retiring a product.
        </p>

        <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          {relatedTools.map((tool) => (
            <Link
              key={tool.href}
              href={tool.href}
              className="rounded-xl border border-blue-500 bg-white p-4 text-sm font-bold text-blue-700 hover:bg-blue-100"
            >
              {tool.title}
            </Link>
          ))}
        </div>
      </section>

      <section className="mt-8 rounded-2xl border border-gray-300 bg-white p-6">
        <h2 className="text-2xl font-bold text-gray-950">
          Simple Etsy listing ROI workflow
        </h2>

        <div className="mt-6 grid gap-5 md:grid-cols-4">
          {workflow.map((step) => (
            <div key={step.title} className="rounded-xl bg-gray-50 p-4">
              <h3 className="font-bold text-gray-950">{step.title}</h3>

              <p className="mt-3 text-sm leading-6 text-gray-600">
                {step.description}
              </p>
            </div>
          ))}
        </div>
      </section>

      <section className="mt-8 grid gap-8 lg:grid-cols-2">
        <div className="rounded-2xl border border-gray-300 bg-white p-6">
          <h2 className="text-2xl font-bold text-gray-950">
            What Etsy sellers should include
          </h2>

          <ul className="mt-5 space-y-3 text-sm leading-6 text-gray-600">
            {checklist.map((item) => (
              <li key={item} className="flex gap-3">
                <span className="mt-1 rounded-full bg-blue-100 px-2 text-xs font-bold text-blue-700">
                  ✓
                </span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>

        <div className="rounded-2xl border border-gray-300 bg-white p-6">
          <h2 className="text-2xl font-bold text-gray-950">
            How to use listing ROI decisions
          </h2>

          <div className="mt-5 space-y-4 text-sm leading-7 text-gray-600">
            <p>
              <strong className="text-gray-950">Keep:</strong> A listing may be
              worth keeping when it produces healthy profit, reasonable margin,
              stable conversion, and manageable fulfillment work.
            </p>

            <p>
              <strong className="text-gray-950">Improve:</strong> A listing may
              need better photos, title, tags, description, price, packaging, or
              shipping setup if traffic exists but conversion is weak.
            </p>

            <p>
              <strong className="text-gray-950">Advertise:</strong> Ads may make
              sense when the listing already converts and has enough margin to
              absorb ad cost.
            </p>

            <p>
              <strong className="text-gray-950">Retire:</strong> A listing may
              be worth retiring when it repeatedly loses money, creates too many
              issues, or requires too much time for too little return.
            </p>
          </div>
        </div>
      </section>

      <section className="mt-8 rounded-2xl border border-amber-300 bg-amber-50 p-5">
        <p className="text-sm leading-6 text-amber-900">
          Etsy listing performance, search visibility, ad results, conversion
          rates, fees, refunds, fulfillment costs, and marketplace rules can
          change. This guide is for planning purposes. Always review actual shop
          analytics, order costs, and current Etsy settings before making listing
          decisions.
        </p>
      </section>
    </main>
  );
}