import Link from "next/link";

const roiFactors = [
  {
    title: "Listing revenue",
    description:
      "The total money an Amazon listing brings in before subtracting referral fees, fulfillment costs, product cost, PPC, refunds, storage, and other expenses.",
  },
  {
    title: "Listing profit",
    description:
      "The money left after all listing-level costs are subtracted from the revenue generated by that product.",
  },
  {
    title: "PPC and promotion cost",
    description:
      "Ad spend, coupons, deals, discounts, and promotions can increase visibility, but they reduce return if the listing does not generate enough profit.",
  },
  {
    title: "Conversion rate",
    description:
      "The percentage of sessions that turn into orders. Low conversion can make PPC, restocking, and listing optimization less efficient.",
  },
  {
    title: "Refund and return losses",
    description:
      "Refunds, returns, damaged inventory, case losses, replacements, and customer issues can reduce real listing return.",
  },
  {
    title: "Time and inventory cost",
    description:
      "Listings may require photo updates, copy edits, keyword work, customer support, inventory checks, restocking, storage, and cash tied up in stock.",
  },
];

const calculators = [
  ["/amazon/listing-roi-calculator", "Amazon Listing ROI Calculator"],
  ["/amazon/conversion-rate-calculator", "Amazon Conversion Rate Calculator"],
  ["/amazon/ppc-roi-calculator", "Amazon PPC ROI Calculator"],
  ["/amazon/profit-calculator", "Amazon Profit Calculator"],
];

const workflow = [
  {
    title: "Measure revenue",
    description:
      "Start with listing revenue during a clear review period.",
  },
  {
    title: "Subtract costs",
    description:
      "Include product cost, Amazon fees, fulfillment, storage, PPC, refunds, maintenance, and support time.",
  },
  {
    title: "Review conversion",
    description:
      "Check sessions, orders, conversion rate, ad performance, and buyer behavior before deciding what to change.",
  },
  {
    title: "Choose an action",
    description:
      "Keep, improve, advertise, restock, discount, bundle, or retire the listing based on real return.",
  },
];

export default function AmazonListingRoiGuidePage() {
  return (
    <main className="mx-auto max-w-6xl px-6 py-12">
      <section className="max-w-3xl">
        <p className="text-sm font-bold uppercase tracking-wide text-blue-700">
          Amazon Seller Guide
        </p>

        <h1 className="mt-3 text-4xl font-bold tracking-tight text-gray-950">
          Amazon Listing ROI Guide
        </h1>

        <p className="mt-4 text-lg leading-8 text-gray-600">
          Amazon listing ROI helps sellers decide whether a product is worth
          keeping, improving, advertising, restocking, discounting, bundling, or
          retiring. A listing can generate sales while still producing weak
          return if referral fees, fulfillment costs, product cost, PPC, storage,
          refunds, maintenance time, and inventory risk are not included.
        </p>
      </section>

      <section className="mt-10 rounded-2xl border border-gray-300 bg-white p-6">
        <h2 className="text-2xl font-bold text-gray-950">
          Amazon listing ROI factors sellers should understand
        </h2>

        <div className="mt-6 grid gap-5 md:grid-cols-2">
          {roiFactors.map((factor) => (
            <div key={factor.title} className="rounded-xl bg-gray-50 p-5">
              <h3 className="font-bold text-gray-950">{factor.title}</h3>
              <p className="mt-3 text-sm leading-6 text-gray-600">
                {factor.description}
              </p>
            </div>
          ))}
        </div>
      </section>

      <section className="mt-8 grid gap-8 lg:grid-cols-2">
        <div className="rounded-2xl border border-gray-300 bg-white p-6">
          <h2 className="text-2xl font-bold text-gray-950">
            Why Amazon listing ROI matters
          </h2>

          <div className="mt-4 space-y-4 text-sm leading-7 text-gray-600">
            <p>
              An Amazon listing can look successful from revenue alone while
              still earning less than expected after referral fees, fulfillment
              costs, PPC, refunds, storage, product cost, and support work are
              included.
            </p>

            <p>
              Listing ROI helps sellers compare products more fairly. A product
              with fewer orders may be better than a higher-volume listing if it
              has stronger margin, fewer returns, lower ad cost, easier
              fulfillment, and less support time.
            </p>

            <p>
              The safest approach is to review listing performance by profit,
              margin, conversion, refund risk, ad cost, and time required before
              deciding whether to keep, improve, promote, restock, or retire the
              listing.
            </p>
          </div>
        </div>

        <div className="rounded-2xl border border-gray-300 bg-white p-6">
          <h2 className="text-2xl font-bold text-gray-950">
            Common Amazon listing ROI mistakes
          </h2>

          <ul className="mt-5 space-y-3 text-sm leading-6 text-gray-600">
            {[
              "Judging listings by sales volume instead of net profit after all costs.",
              "Increasing PPC spend without checking whether ROI improves.",
              "Keeping listings active when they repeatedly lose money after storage, PPC, refunds, or support time.",
              "Ignoring time spent revising listings, answering messages, restocking, and handling issues.",
              "Comparing revenue across listings without comparing margin and return on effort.",
              "Retiring listings too quickly without testing photos, title, bullets, price, keywords, or offer quality.",
            ].map((item) => (
              <li key={item} className="flex gap-3">
                <span className="mt-1 rounded-full bg-red-100 px-2 text-xs font-bold text-red-600">
                  ×
                </span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>
      </section>

      <section className="mt-8 rounded-2xl border border-blue-300 bg-blue-50 p-6">
        <h2 className="text-2xl font-bold text-gray-950">
          Useful Amazon listing ROI calculators
        </h2>

        <p className="mt-3 text-sm leading-6 text-gray-700">
          Use these tools to estimate listing return, conversion, PPC impact,
          sales goals, profit, and restock decisions before changing a listing
          strategy.
        </p>

        <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          {calculators.map(([href, label]) => (
            <Link
              key={href}
              href={href}
              className="rounded-xl border border-blue-500 bg-white p-4 text-sm font-bold text-blue-700 hover:bg-blue-100"
            >
              {label}
            </Link>
          ))}
        </div>
      </section>

      <section className="mt-8 rounded-2xl border border-gray-300 bg-white p-6">
        <h2 className="text-2xl font-bold text-gray-950">
          Simple Amazon listing ROI workflow
        </h2>

        <div className="mt-6 grid gap-5 md:grid-cols-4">
          {workflow.map((step) => (
            <div key={step.title} className="rounded-xl bg-gray-50 p-4">
              <h3 className="font-bold text-gray-950">{step.title}</h3>
              <p className="mt-3 text-sm leading-6 text-gray-600">
                {step.description}
              </p>
            </div>
          ))}
        </div>
      </section>

      <section className="mt-8 grid gap-8 lg:grid-cols-2">
        <div className="rounded-2xl border border-gray-300 bg-white p-6">
          <h2 className="text-2xl font-bold text-gray-950">
            What Amazon sellers should include
          </h2>

          <ul className="mt-5 space-y-3 text-sm leading-6 text-gray-600">
            {[
              "Listing revenue over the review period.",
              "Product cost, referral fees, FBA or FBM fulfillment costs, shipping, packaging, storage, and labor.",
              "PPC spend, coupons, deals, listing updates, photography, copywriting, and optimization work.",
              "Refunds, returns, cancellations, damaged inventory, replacement shipments, and case losses.",
              "Time spent revising, supporting, restocking, packing, and managing the listing.",
              "Sessions, orders, conversion rate, buy box performance, search visibility, and traffic quality.",
            ].map((item) => (
              <li key={item} className="flex gap-3">
                <span className="mt-1 rounded-full bg-blue-100 px-2 text-xs font-bold text-blue-700">
                  ✓
                </span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>

        <div className="rounded-2xl border border-gray-300 bg-white p-6">
          <h2 className="text-2xl font-bold text-gray-950">
            How to use Amazon listing ROI decisions
          </h2>

          <div className="mt-5 space-y-4 text-sm leading-7 text-gray-600">
            <p>
              <strong className="text-gray-950">Keep:</strong> A listing may be
              worth keeping when it produces healthy profit, reasonable margin,
              stable conversion, and manageable fulfillment work.
            </p>

            <p>
              <strong className="text-gray-950">Improve:</strong> A listing may
              need better photos, title, bullets, keywords, pricing, shipping
              setup, or description if traffic exists but conversion is weak.
            </p>

            <p>
              <strong className="text-gray-950">Promote:</strong> Ads may make
              sense when the listing already covers costs and has enough margin
              to absorb PPC.
            </p>

            <p>
              <strong className="text-gray-950">Retire:</strong> A listing may
              be worth retiring if it repeatedly loses money, creates too many
              issues, ties up inventory, or requires too much time for too
              little return.
            </p>
          </div>
        </div>
      </section>

      <section className="mt-8 rounded-2xl border border-gray-300 bg-white p-6">
        <h2 className="text-2xl font-bold text-gray-950">
          Ways to improve Amazon listing ROI
        </h2>

        <div className="mt-6 grid gap-5 md:grid-cols-4">
          {[
            [
              "Improve conversion",
              "Upgrade photos, title, bullets, keywords, price, reviews, and offer quality.",
            ],
            [
              "Reduce ad waste",
              "Lower PPC spend on search terms, campaigns, or placements that do not generate profitable orders.",
            ],
            [
              "Raise profit per order",
              "Improve sourcing, pricing, fulfillment cost, shipping setup, bundles, coupons, and refund prevention.",
            ],
            [
              "Retire weak listings",
              "Remove or revise listings that repeatedly lose money, require too much support, or tie up capital.",
            ],
          ].map(([title, text]) => (
            <div key={title} className="rounded-xl bg-gray-50 p-4">
              <h3 className="font-bold text-gray-950">{title}</h3>
              <p className="mt-3 text-sm leading-6 text-gray-600">{text}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="mt-8 rounded-2xl border border-amber-300 bg-amber-50 p-5">
        <p className="text-sm leading-6 text-amber-900">
          Amazon listing performance, search visibility, buy box behavior, PPC
          results, conversion rates, referral fees, fulfillment costs, refunds,
          inventory limits, taxes, and marketplace policies can change. This
          guide is for planning purposes. Always review actual order costs,
          seller reports, and current Amazon seller settings before making
          listing decisions.
        </p>
      </section>
    </main>
  );
}