import Link from "next/link";

export default function EbayListingRoiGuidePage() {
  return (
    <main className="mx-auto max-w-6xl px-6 py-12">
      <section className="max-w-3xl">
        <p className="text-sm font-bold uppercase tracking-wide text-blue-700">
          eBay Seller Guide
        </p>

        <h1 className="mt-3 text-4xl font-bold tracking-tight text-gray-950">
          eBay Listing ROI Guide
        </h1>

        <p className="mt-4 text-lg leading-8 text-gray-600">
          eBay listing ROI helps sellers decide whether a listing is worth
          keeping, improving, promoting, restocking, discounting, or retiring. A
          listing can generate sales while still producing weak return if fees,
          shipping, item cost, labor, refunds, ad spend, and maintenance time
          are not included.
        </p>
      </section>

      <section className="mt-10 rounded-2xl border border-gray-300 bg-white p-6">
        <h2 className="text-2xl font-bold text-gray-950">
          eBay listing ROI factors sellers should understand
        </h2>

        <div className="mt-6 grid gap-5 md:grid-cols-2">
          {[
            [
              "Listing revenue",
              "The total money a listing brings in before subtracting eBay fees, item cost, shipping, packaging, ads, returns, and refunds.",
            ],
            [
              "Listing profit",
              "The money left after subtracting all listing-related costs from the revenue generated by that product.",
            ],
            [
              "Promoted listing cost",
              "Ad spend or promoted listing fees can improve visibility, but they reduce return if the listing does not generate enough profit.",
            ],
            [
              "Conversion rate",
              "The percentage of listing views that turn into orders. Low conversion can make ads, restocking, or continued listing work less efficient.",
            ],
            [
              "Refund and return losses",
              "Returns, refunds, damaged packages, case losses, and replacement shipments can reduce real listing return.",
            ],
            [
              "Time and maintenance cost",
              "Listings may require photo updates, title edits, item specifics, messages, inventory checks, relisting, packing, and customer service.",
            ],
          ].map(([title, text]) => (
            <div key={title} className="rounded-xl bg-gray-50 p-5">
              <h3 className="font-bold text-gray-950">{title}</h3>
              <p className="mt-3 text-sm leading-6 text-gray-600">{text}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="mt-8 grid gap-8 lg:grid-cols-2">
        <div className="rounded-2xl border border-gray-300 bg-white p-6">
          <h2 className="text-2xl font-bold text-gray-950">
            Why eBay listing ROI matters
          </h2>

          <div className="mt-4 space-y-4 text-sm leading-7 text-gray-600">
            <p>
              A listing can look successful from sales volume alone while still
              earning less than expected after eBay fees, shipping, item cost,
              packaging, promoted listing fees, refunds, and labor are included.
            </p>

            <p>
              Listing ROI helps sellers compare products more fairly. A listing
              with fewer sales may be better than a high-volume listing if it has
              stronger margin, fewer returns, lower ad cost, easier shipping, and
              less support time.
            </p>

            <p>
              The safest approach is to review listing performance by profit,
              margin, conversion, refund risk, ad cost, and time required before
              deciding whether to keep, improve, promote, restock, or retire the
              listing.
            </p>
          </div>
        </div>

        <div className="rounded-2xl border border-gray-300 bg-white p-6">
          <h2 className="text-2xl font-bold text-gray-950">
            Common eBay listing ROI mistakes
          </h2>

          <ul className="mt-5 space-y-3 text-sm leading-6 text-gray-600">
            {[
              "Judging listings by sales volume instead of net profit after costs.",
              "Increasing promoted listing spend before checking whether ROI improves.",
              "Keeping listings active when they repeatedly lose money after refunds or ad costs.",
              "Ignoring time spent revising listings, answering messages, restocking, or handling issues.",
              "Comparing revenue across listings without comparing margin and return on effort.",
              "Retiring listings too quickly without testing photos, title, item specifics, pricing, and shipping.",
            ].map((item) => (
              <li key={item} className="flex gap-3">
                <span className="mt-1 rounded-full bg-red-100 px-2 text-xs font-bold text-red-600">
                  ×
                </span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>
      </section>

      <section className="mt-8 rounded-2xl border border-blue-300 bg-blue-50 p-6">
        <h2 className="text-2xl font-bold text-gray-950">
          Useful eBay listing ROI calculators
        </h2>

        <p className="mt-3 text-sm leading-6 text-gray-600">
          Use these tools to estimate listing return, conversion, promoted
          listing impact, sales goals, profit, and restock decisions before
          changing a listing strategy.
        </p>

        <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          {[
            ["/ebay/listing-roi-calculator", "eBay Listing ROI Calculator"],
            ["/ebay/conversion-rate-calculator", "eBay Conversion Rate Calculator"],
            [
              "/ebay/promoted-listing-roi-calculator",
              "eBay Promoted Listing ROI Calculator",
            ],
            ["/ebay/profit-calculator", "eBay Profit Calculator"],
          ].map(([href, label]) => (
            <Link
              key={href}
              href={href}
              className="rounded-xl border border-blue-500 bg-white p-4 text-sm font-bold text-blue-700 hover:bg-blue-100"
            >
              {label}
            </Link>
          ))}
        </div>
      </section>

      <section className="mt-8 rounded-2xl border border-gray-300 bg-white p-6">
        <h2 className="text-2xl font-bold text-gray-950">
          Simple eBay listing ROI workflow
        </h2>

        <div className="mt-6 grid gap-5 md:grid-cols-4">
          {[
            [
              "Measure revenue",
              "Start with listing sales revenue during a clear review period.",
            ],
            [
              "Subtract costs",
              "Include eBay fees, item cost, shipping, packaging, ads, labor, refunds, and replacements.",
            ],
            [
              "Review conversion",
              "Check views, orders, conversion rate, and ad performance before deciding what to change.",
            ],
            [
              "Choose an action",
              "Keep, improve, advertise, restock, discount, bundle, or retire the listing based on real return.",
            ],
          ].map(([title, text]) => (
            <div key={title} className="rounded-xl bg-gray-50 p-4">
              <p className="font-bold text-gray-950">{title}</p>
              <p className="mt-3 text-sm leading-6 text-gray-600">{text}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="mt-8 grid gap-8 lg:grid-cols-2">
        <div className="rounded-2xl border border-gray-300 bg-white p-6">
          <h2 className="text-2xl font-bold text-gray-950">
            What eBay sellers should include
          </h2>

          <ul className="mt-5 space-y-3 text-sm leading-6 text-gray-600">
            {[
              "Listing revenue over the review period.",
              "Profit per order after eBay fees, item cost, shipping, packaging, and labor.",
              "Promoted listing cost, listing fees, store costs, and optional listing upgrades.",
              "Refunds, returns, cancellations, damaged item losses, and replacement shipments.",
              "Time spent revising, supporting, restocking, packing, and managing the listing.",
              "Views, orders, conversion rate, active listing count, sold comps, and traffic quality.",
            ].map((item) => (
              <li key={item} className="flex gap-3">
                <span className="mt-1 rounded-full bg-blue-100 px-2 text-xs font-bold text-blue-700">
                  ✓
                </span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>

        <div className="rounded-2xl border border-gray-300 bg-white p-6">
          <h2 className="text-2xl font-bold text-gray-950">
            How to use eBay listing ROI decisions
          </h2>

          <div className="mt-5 space-y-4 text-sm leading-7 text-gray-600">
            <p>
              <strong className="text-gray-950">Keep:</strong> A listing may be
              worth keeping when it produces healthy profit, reasonable margin,
              stable conversion, and manageable fulfillment work.
            </p>

            <p>
              <strong className="text-gray-950">Improve:</strong> A listing may
              need better photos, title, item specifics, pricing, shipping
              setup, or description if traffic exists but conversion is weak.
            </p>

            <p>
              <strong className="text-gray-950">Promote:</strong> Ads may make
              sense when the listing already covers costs and has enough margin
              to absorb promoted listing fees.
            </p>

            <p>
              <strong className="text-gray-950">Retire:</strong> A listing may
              be worth retiring if it repeatedly loses money, creates too many
              issues, ties up inventory, or requires too much time for too little
              return.
            </p>
          </div>
        </div>
      </section>

      <section className="mt-8 rounded-2xl border border-gray-300 bg-white p-6">
        <h2 className="text-2xl font-bold text-gray-950">
          Ways to improve eBay listing ROI
        </h2>

        <div className="mt-6 grid gap-5 md:grid-cols-4">
          {[
            [
              "Improve conversion",
              "Upgrade photos, title, item specifics, condition notes, shipping options, and buyer trust signals.",
            ],
            [
              "Reduce ad waste",
              "Lower promoted listing cost on weak listings or focus spend on proven profitable listings.",
            ],
            [
              "Raise profit per order",
              "Improve sourcing, pricing, shipping, packaging, and offer strategy to increase contribution.",
            ],
            [
              "Retire weak listings",
              "Remove or revise listings that repeatedly lose money, require too much support, or tie up capital.",
            ],
          ].map(([title, text]) => (
            <div key={title} className="rounded-xl bg-gray-50 p-4">
              <p className="font-bold text-gray-950">{title}</p>
              <p className="mt-3 text-sm leading-6 text-gray-600">{text}</p>
            </div>
          ))}
        </div>
      </section>

      <div className="mt-8 rounded-2xl border border-amber-300 bg-amber-50 p-5 text-sm leading-6 text-amber-900">
        eBay listing performance, search visibility, promoted listing results,
        conversion rates, fees, refunds, fulfillment costs, taxes, buyer demand,
        and marketplace rules can change. This guide is for planning purposes.
        Always review actual order costs, current eBay settings, and real
        listing performance before making listing decisions.
      </div>
    </main>
  );
}